feat: Push to releases

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -39,3 +39,19 @@ jobs:
           file: target/coverage.out
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      - name: Upload to GitHub Releases
+        run: |
+          TAG_NAME="v$VERSION"
+          RESPONSE=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -X POST -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"$TAG_NAME\"}" "https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/releases")
+          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')
+          if [ "$RELEASE_ID" = "" ]; then
+            echo "Failed to create github release"
+            exit 1
+          fi
+          RESPONSE=$(curl -sSL "${HEADERS[@]}" --data-binary @"target/$BIN_NAME" "https://uploads.github.com/repos/${{ env.GITHUB_REPOSITORY }}/releases/$RELEASE_ID/assets?name=$BIN_NAME")
+          if [[ "$(echo "$RESPONSE" | jq -r '.id')" != null ]]; then
+            echo "Asset uploaded successfully!"
+          else
+            echo "Failed to upload asset. RESPONSE: $RESPONSE"
+            exit 1
+          fi
